### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by dancinglightning** [nirnanaaa/gollum_rails#30]
Moi, nice sounding project, so i thought i let you know that it's impossible to try out with current versions.
I did rails new and then added the gollum_rails gem and bundled:

    gollum_rails (>= 0) ruby depends on
      gollum-lib (~> 4.0.1) ruby depends on
        gollum-grit_adapter (>= 0.1.1, ~> 0.1) ruby depends on
          gitlab-grit (>= 2.7.1, ~> 2.7) ruby depends on
            mime-types (~> 1.15) ruby

    rails (= 4.2.0) ruby depends on
      actionmailer (= 4.2.0) ruby depends on
        mail (>= 2.5.4, ~> 2.5) ruby depends on
          mime-types (2.4.3)

I tried with 3.2 and got it up (in a new app) and it doesn't have any routes! 
I can see that approach, but it should be mentioned. The install instructions make it sound like gem and path and good to go.

So i cloned the repository and stumbled again. It's not an app.

Maybe my confusion comes from the readme, where it says you "can define your own views".
I assumed that means there are views which i can redefine/overwrite.
It looks like it would be better to say "you must define your own views".

btw: i've just written a few engines and this would be a good candidate for an engine. Let me know if you want some help / talk .

Torsten

**Comment by seanosaur** [comment]
I just followed the breadcrumb trail all the way to gitlab's grit repo and saw that you had already posted an issue about updating mime-types. I guess this won't work until then?

**Comment by dancinglightning** [comment]
I cloned the grit and changed its gemspec and used the :path syntax to point to that and got it up.

**Comment by seanosaur** [comment]
That did the trick, thanks!

**Comment by dancinglightning** [comment]
btw: it is also quite a simple matter to mount gollum (the sinatra app) into a rails app. 
You can google it, i found it on stackoverflow. Off course you can't override anything, but you get a working wiki with 8 lines of code.
The trick i said was actually during that tryout, but glad it worked.
We'll since i wrote so much, here is the code (with the adjusted grit) 
Gemfile:
gem "gollum" , :path => "../gollum"
gem "gitlab-grit" , :path => "../grit" 

config/routes.rb:
require 'gollum/app'

Rails.application.routes.draw do
  Precious::App.set(:gollum_path, Rails.root.join('wiki').to_s)
  Precious::App.set(:default_markup, :markdown) # set your favorite markup language
  Precious::App.set(:wiki_options, {:universal_toc => false , :allow_editing => true })
  mount Precious::App, at: '/wiki'
end

and you have to create the wiki's git by 
mkdir wiki;cd wiki; giti init --bare

Quite impressive in it's own way, but i hope we can get it better with this repo.

**Comment by nirnanaaa** [comment]
@seanosaur @dancinglightning Sorry for my late response. This does indeed work except for binary encoding. There is an error encoding a letter, which should return UTF-8 but it returns ASCI-8bit, which should be a subencoding of utf-8 but... It blocks travis from passing.

**Comment by nirnanaaa** [comment]
@dancinglightning Will read your posts ASAP. Soo busy at work.

**Comment by nirnanaaa** [comment]
This is fixed in a gollum-lib and grit ticket, as gollum-lib does not depend on gollum-lib anymore
