### ISSUE TITLE
Unclear folder support status

### ISSUE THREAD

**Issue by hiro2016** [nirnanaaa/gollum_rails#35]
Firstly thanks for writing a nice gem.

Since usage example contained reference to `Page.all(:folder,'articles')`, I tried to make gollum_rails work with folders but I feel it's not really a trivial task.  
 
+ Rails assume Page resources are accessible with "pages/:id" combination   
  + path helpers messed up  
Overriding helpers in page_helper.rb solved  

  + rails routes require customization
```
  match "pages/:id/edit", id: /.*/, via: :get, to: "pages#edit", as: :edit_page
  match "pages/", id: /.*/, via: :patch, to: "pages#update"
  match "pages/", id: /.*/, via: :get, to: "pages#show", as: :page, anchor: false
```

+ Once a file is created under a folder, all file creations thereafter happen under that folder.
Create a file `fol/test` => url method returns `fol/test`  
Create a file `at_root` => url method returns `fol/at_root`    

+ Using folder breaks rails form builders

  
I don't know much about rails, so I could be doing something wildly wrong.  
And I guess I can solve the issues with some effort, but not too easily...  
It would be nice if you could leave us some note on how to deal with folder related issues or simple warn that it's not supported.  
Thanks for reading.  

## Note for myself and for others  

+ form builder post address issue in edit form
Explicitly provide url
```
<%= form_with(model: @page, url:"/"+@page.url,local: true ) do |form| %>
```  

+ Getting stuck at a folder  
```
  include GollumRails::Core::ClassMethods
  def index
    reset_folder
    @pages = Page.all
  end
```

### Using revert_page method
controller
```
    def revert
     # before_action sets @page prior to revert method call
      r = Page.wiki.revert_page(@page, params[:sha],@page.current_version)
      if r == nil|| r == false
        flash[:danger] = "Failed to revert the page"
      else
        flash[:success] = "Page successfully reverted"
      end
      path = "/"+page_path(@page).to_s
      redirect_to path
    end
```
model
```
    class Page < GollumRails::Page
      def url
        "pages/#{super}"
      end
      def path
        Page.wiki.path
      end
      def self.strip_filename(filename)
        ::File.basename(filename, ::File.extname(filename))
      end
      def filename_stripped
        self.class.strip_filename(filename)
      end
    end
```
erb template example for revert page action
```
    <head>
    <link rel="stylesheet" type="text/css" href="/dist/diff2html.css">
    <!-- Javascripts -->
    <script type="text/javascript" src="/dist/diff2html.js"></script>
    <script type="text/javascript" src="/dist/diff2html-ui.js"></script>
    </head>
    <% count = 0 %>
    <%= prv_sha = @page.current_version %>
    <% if @page != nil %>
      <% for h in @page.history[1...@page.history.length] do %>
        <h3><%= @page.history[count].author.name %></h3>

        <div style="display:block;">
        <%= button_to 'Revert to this', 
          {controller: "pages",
           action: "revert", 
           sha: "#{h.sha}"
          },
          method: :post,
          style: "width:200px;float:right;margin:10px;", 
          class: "btn btn-primary",
          type: "button"%>
        </div>
        <div id="diff_output<%= count %>" [innerHtml]="outputHtml"></div>
       <script>
        var inputString = "<%= escape_javascript(@page.compare_commits(h.sha,prv_sha)) %>";
        var diff2htmlUi = new Diff2HtmlUI( {diff:  inputString }); 
        diff2htmlUi.draw('div#diff_output<%= count %>', {inputFormat: 'json', showFiles: true, matching: 'lines'});
       </script>
      <% count += 1 %>
      <% prv_sha = h.sha %>
      <% end %>
    <% end %>
```  
I experienced some troubles using `@page.history`.  
`@page.history.first.sha` contains the sha for the latest commit.  
` Page.wiki.revert_page(@page, @page.history.first.sha,@page.current_version)` throws no such method diff error at `repo.diff(sha2, sha1, path).first.diff` as `repo.diff(sha2, sha1, path)` returns an empty [] when sha1 is the sha for the current commit.    
The code is in gollum-lib, so not related to gollum_rails though.

**Comment by nirnanaaa** [comment]
hey there,

it's been a while since i last touched ground with this gem.

maybe it's worth taking a look at these resources?

https://github.com/nirnanaaa/gollum_redmine/blob/master/app/controllers/pages_controller.rb
https://github.com/nirnanaaa/gollum_redmine/blob/master/app/models/gpage.rb
https://github.com/nirnanaaa/gollum_redmine/blob/master/config/routes.rb#L22

this gem should only be used in combination with your own controller magic. 

hope this helps and maybe you can extract some relevant info for your project!

**Comment by hiro2016** [comment]
Thank you very much.   
Looks like all I need are in those posts.    
  
Sorry about taking your time.   
Have a good day.

**Comment by nirnanaaa** [comment]
no worries. feel free to open a ticket at any time!
